name: Deploy to GitHub Pages

on:
  # Déclencher le workflow à chaque push sur la branche `main`
  push:
    branches: [ main ]
  # Permet de lancer le workflow manuellement depuis l'onglet Actions sur GitHub
  workflow_dispatch:

# Permissions nécessaires pour cloner le repo et déployer les pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies using npm
        run: npm install

      - name: Build the site with Astro
        run: npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # Spécifie la branche pour GitHub Pages
          folder: dist       # Le dossier à déployer
